export const ERRORS = {
  INVALID_ADDRESS: "INVALID_ADDRESS",
  WALLET_ALREADY_EXISTS: "WALLET_ALREADY_EXISTS",
  WALLET_LIMIT_REACHED: "WALLET_LIMIT_REACHED",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
};
